alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'
alias c='clear'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias la='ls -a1'
alias ls='ls --color=auto'
alias open='xdg-open'
alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'
alias rm='trash'
alias aptup='sudo apt update'
alias sourceme='source ~/.bashrc'
alias cat='bat'
alias ls='exa'
alias ps='procs'
alias top='bottom'
alias find='fd'
