aaron-bond.better-comments
alexcvzz.vscode-sqlite
bmewburn.vscode-intelephense-client
christian-kohler.npm-intellisense
cschlosser.doxdocgen
dbaeumer.vscode-eslint
eamodio.gitlens
ecmel.vscode-html-css
eg2.vscode-npm-script
emmanuelbeziat.vscode-great-icons
Equinusocio.vsc-community-material-theme
esbenp.prettier-vscode
foxundermoon.shell-format
GitHub.copilot
GitHub.copilot-labs
golang.go
jeff-hykin.better-cpp-syntax
josetr.cmake-language-support-vscode
leizongmin.node-module-intellisense
mikestead.dotenv
mquandalle.graphql
ms-azuretools.vscode-docker
ms-dotnettools.vscode-dotnet-runtime
ms-python.isort
ms-python.pylint
ms-python.python
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-slideshow
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-vscode.remote-explorer
ms-vscode.vscode-typescript-tslint-plugin
redhat.vscode-yaml
Remisa.shellman
rust-lang.rust-analyzer
svelte.svelte-vscode
twxs.cmake
vsciot-vscode.vscode-arduino
vscode-icons-team.vscode-icons
yzhang.markdown-all-in-one
