EditorConfig.editorconfig
abusaidm.html-snippets
aaron-bond.better-comments
akamud.vscode-theme-onedark
austin.code-gnu-global
awesomektvn.scratchpad
bungcip.better-toml
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
cssho.vscode-svgviewer
dbaeumer.vscode-eslint
dbaeumer.vscode-eslint
dbaeumer.vscode-eslint
dsznajder.es7-react-js-snippets
eamodio.gitlens
editorconfig.editorconfig
eg2.vscode-npm-script
equinusocio.vsc-community-material-theme
equinusocio.vsc-material-theme
equinusocio.vsc-material-theme
equinusocio.vsc-material-theme-icons
hookyqr.beautify
jasonnutter.search-node-modules
jithurjacob.nbpreviewer
jpoissonnier.vscode-styled-components
leizongmin.node-module-intellisense
mikestead.dotenv
ms-azuretools.vscode-docker
ms-mssql.mssql
ms-python.python
ms-python.python
ms-vscode.atom-keybindings
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.csharp
ms-vscode.csharp
ms-vscode.go
msjsdiag.debugger-for-chrome
msjsdiag.debugger-for-chrome
pepri.subtitles-editor
pkief.material-icon-theme
remisa.shellman
robertohuertasm.vscode-icons
rust-lang.rust
stevencl.adddoccomments
vscode-icons-team.vscode-icons
waderyan.nodejs-extension-pack
xabikos.javascriptsnippets
